sudo: required

language: node_js
node_js:

services:
- docker

before_script:
- npm install -g gulp-cli

script:
- gulp test

env:
  global:
  - secure: cBYpi9JAxAzJ3xvzud9XwbaBdLsooICPSmae426qsxgjxyBJsYsfB9DmwgRU1kYAvnU8Mzz3FhuVu9b19XhE9tibNzZdI0EfekhXhVs9/fL6iy9Adcivr0bmI6nKsKBfyojpidY2AXGzLyERmoXRhh99lwuj4PMgEgoaO0mS4iV65Km45cwu1uYCBPaS89oevYe2ZE+vNM7bWwDQtRMyVw5Q613Cj8eOwjayAfnan+ABek8OVYQJNpm49xi4JNdLw1zhuX22lArSy88SpPs2PwMvrmNFZdsW/3/epiraKQ29OVljPKffIshxjmOmltyftWphYQDAJjkd0Em1OhmWa8d3WuTBMutR5HXl4iByK/FafuceaAXKcEfT4OZnlu3WmNKHqA9o+LUjyLorwO/0q5Bd45edlarfjHWqO74D3yYIKU/HoxEoRF1Wh8/fUyS0fpq/fjarfLJlbWMoq/JxhR0D5EyQOLvlBAwSGEI79gv832213AymrWJCviKUvnEnm47PeXXjvNpcTzXmfkY1Cil0zy7ZTDCYOu7CZ5/Fx0/wGedHYH7iqe03pTemP5fIILDD0bd1HVg8wobA6AWApNLTHCy3Yce6ER0fzGrBNxGCqqyuhWZ0mNc58nalAnrZrb7+XaOmUapsxNoCPFYTN5rMRWSz1QXioOq4X4Ub8ik=
  - secure: JKE1XZ3VIXRx5NXxMUnq70w+lufuS3zDyILtYxgU5jmijU952Z8NPNpHIe485rEtFahOaW1xlJSMb62KqXUG3KTwied+FzQRaiEunBy0FjSdCai/o4uC8bCwiikR7UlZs1IJNhVpc1N8PLqoC60oiOUzd0+Cuq6V1e69i1A6+vvamwoPLeAIt34OGkaI4lxCQd4WL1UilOnV7qtXcQlBb9gozG38Dwf5p6K+7l39YeIuCoBZpKYSd44JUvfaLxW9zuowEO8H40y+s/6xcTjDH4GtlbzCFh2GiHWNbDjMpkHYGNYh/zoTkj+9GhrXosCoUleqaJ8ArCHiiGb55KXi3GcZYKzH6NRziqXCmy6anponcmZOYEoXS10LcfAfYI5mDgCI8XtjH7UjWMbcvb+KY/Yw7ov85ta68rUdPHcEhjNaOou67EG8cTei/MDzJQTapmwKDUZ1eH8OwLv0uJgPyJuwpmJuD2CbDXGjlxv5dNCCf79yXNcaTGAq6RoLxGg/qtDDluoA/qcJ2dcNxqQvja574W7U9UCcDTWETdcTZIpQLYX17+yvV0/aKqY93JN/7fwiYi50UidgxQ7y86X1ruTYt2LAeJOXzQTNYPdavz1EWv1aQ9HxGNdjCiIqBjTuGvnJz2GU/vN6mnT5vnWZvIpkzi6/KXvjfU2gpguA7EQ=

deploy:
- provider: script
  script: bin/docker/build.sh
  on:
    branch: master
