version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: mongod --smallfiles

    scraper:
        build: .
        container_name: gp-trending-scraper
        environment:
            LOGGER_NAME: GP-Trending-Scraper
            LOGGER_LEVEL: trace
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_DB: gitpoint
            CRON_PATTERN: '0 * * * * *'
            CRON_TIMEZONE: 'Europe/Amsterdam'
            HTTP_PORT: 1337
        depends_on:
            - "mongodb"
        volumes:
            - "./:/opt/app"
        ports:
            - 1337:1337
